Make nyt clone
vitorelourenco/NewYorkTimesClone pull request #2
Opened 2021-02-17 19:52 UTC by vitorelourenco

Linter checks were added to GitHub Actions
reset.css file included
The structure and content of the NYT page was laid out in html.
The images were downloaded from the website and the SVG icons were copied from the source when available.
The fonts used in the clone are either georgia or the browsers default since the original fonts aren't available for download. 
The header and central column containing the main content of the page were positioned using display: flex.
The Editor's Pick section was placed to the right using float:right and the <aside> tag. This section is currently contained by a div.
The middle section containing links to other articles (between the page's footer and the main content) was built using display: grid.
The bottom section was also built using display: grid , the links weren't added to the respective hrefs of the anchors.
The nav element was fixed to the top and it's elements positioned with display:flex
The fixed-footer element was fixed to the bottom and it's element is positioned using display:flex
A README.md file was written using Microverse's template and the feature branch was deployed. The link to the live version can be found in the README.md file.

2021-02-17 20:58 UTC, wathigo requested changes
## CHANGES REQUIRED :o: 
Great job on this project.
Let's make a few changes before we move on. See the comments :point_down: 

**After making the changes, submit another request for review.**

**Happy Coding :technologist: 
Simon Wathigo**

2021-02-17 20:58 UTC, wathigo commented on index.html
> +            <div id="nav-center">
**REQUIRED**
The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

2021-02-17 20:58 UTC, wathigo commented on index.html
> +                        </div>
**REQUIRED**
It uses an anchor tag, any valid value e.g. "#" is okay for it's `href` attribute, to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

2021-02-17 21:05 UTC, vitorelourenco commented on index.html
> +            <div id="nav-center">
change made and pushed

2021-02-17 21:11 UTC, vitorelourenco commented on index.html
> +                        </div>
requested changes were made to this block of code plus the two other blocks following it. changes pushed

2021-02-17 21:43 UTC, blackpintz requested changes
# Status: Changes Required 🛑 

## Hello team 👋,

**Great job implementing the requested changes 👏.**

### Highlights.

- **The page looks like the original.**

### Mandatory requirements

- **The new york times logo at the footer should be a link as well.**
- **Wrap your footer section in a `footer` tag instead of `div` tag.**

### Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

2021-02-17 21:52 UTC, vitorelourenco commented
> # Status: Changes Required stop_sign
> ## Hello team wave,
> 
> **Great job implementing the requested changes clap.**
> ### Highlights.
> 
>     * **The page looks like the original.**
> 
> 
> ### Mandatory requirements
> 
>     * **The new york times logo at the footer should be a link as well.**
> 
>     * **Wrap your footer section in a `footer` tag instead of `div` tag.**
> 
> 
> ### Happy coding clinking_glasses.
> 
> **You can reach me on slack (Rose Wanjohi).**

changed <div> to <footer> and made the NYT footer logo into a link

2021-02-18 00:03 UTC, enaburekhan approved these changes
# Status: Project Approved:heavy_check_mark:
Hi Vitor!
Great job on implementing all the changes requested by the previous Tse:clap::clap:. The project looks exactly like the original. Keep up the good work:thumbsup:
Move on with your next task:walking:.

You can drop your questions:point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy Coding:blush:
Eric Enaburekhan

2021-02-18 13:16 UTC, merged